language: csharp
dotnet: 2.1.4
solution: PeselValidator.sln
install:
  - dotnet restore PeselValidator.sln
script:
  - dotnet build -c Release PeselValidator.sln
  - dotnet test ./PeselValidatorTests/PeselValidatorTests.csproj