language: csharp
mono: none
dotnet: 2.1.4
solution: PeselValidator.sln
install:
  - dotnet restore PeselValidator.sln
script:
  - dotnet build -c Release PeselValidator.sln
  - dotnet test ./PeselValidatorTests/PeselValidatorTests.csproj
after_success:
  - test $TRAVIS_BRANCH = "master" && dotnet nuget push ./PeselValidator/bin/Release/Rychusoft.Validators.PeselValidator.*.nupkg -k $NugetApiKey