language: csharp
mono: none
dotnet: 2.1.4
solution: PeselValidator.sln
install:
  - dotnet restore PeselValidator.sln
  - dotnet add ./PeselValidatorTests/PeselValidatorTests.csproj package --version 3.7.0 --package-directory testrunner NUnit.Runners
  - sudo apt-get install mono-runtime
script:
  - dotnet build -c Release PeselValidator.sln
  - mono ./testrunner/nunit.consolerunner/3.7.0/tools/nunit3-console.exe ./PeselValidatorTests/bin/Release/netcoreapp2.0/PeselValidatorTests.dll