language: csharp
mono: none
dotnet: 2.1.4
solution: PeselValidator.sln
install:
  - dotnet restore PeselValidator.sln
script:
  - dotnet build -c Release PeselValidator.sln
  - dotnet test ./PeselValidatorTests/PeselValidatorTests.csproj
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./PeselValidator/bin/Release/Rychusoft.Validators.PeselValidator.*.nupkg -k $NugetApiKey
  on: 
    branch master