language: csharp
mono: none
dotnet: 2.1.4
solution: PeselValidator.sln
install:
  - dotnet restore PeselValidator.sln
  - dotnet add package NUnit.Runners -version 3.7.0 --package-directory testrunner
script:
  - xbuild /p:Configuration=Release PeselValidator.sln
  - dotnet ./testrunner/NUnit.Runners.3.7.0/tools/nunit-console.exe ./PeselValidatorTests/bin/Release/netcoreapp2.0/PeselValidatorTests.dll